name: Powershell Local Runner

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  local-build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add Python to PATH
        run: |
          $env:PATH += ';C:\Users\Administrator\AppData\Local\Programs\Python\Python313'
          python --version
          python -m pip --version
        shell: powershell

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        shell: powershell

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --uac-admin --noconsole ascmhl_gui.py
        shell: powershell

      - name: Debug Directory Contents
        run: |
          Get-ChildItem -Path . -Recurse
        shell: powershell

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Build v${{ github.run_number }}
          body: |
            Automated release for build v${{ github.run_number }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/ascmhl_gui.exe
          asset_name: ascmhl_gui.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
